DELETE FROM timeline_events WHERE kind = 'contact_preferences_changed';
ALTER TABLE timeline_events DROP CONSTRAINT chk_timeline_events_kind;
ALTER TABLE timeline_events ADD CONSTRAINT chk_timeline_events_kind CHECK (kind IN ('invoice_due','reminder_drafted','guardrail_passed','guardrail_failed','approved','edited','rejected','sent','send_failed','reply_received','classified','promise_logged','payment_received','payment_matched','promise_fulfilled','promise_partially_fulfilled','promise_missed','dispute_opened','dispute_resolved','escalation_created','escalation_resolved','clock_advanced','dispute_assigned','dispute_investigating','followup_created','followup_closed'));
ALTER TABLE settings DROP COLUMN feature_sms;
ALTER TABLE customers DROP CONSTRAINT chk_customers_preferred_channel, DROP COLUMN contact_consent, DROP COLUMN preferred_channel;
UPDATE agent_runs SET channel = 'email' WHERE channel = 'sms';
ALTER TABLE agent_runs DROP CONSTRAINT chk_agent_runs_channel;
ALTER TABLE agent_runs ADD CONSTRAINT chk_agent_runs_channel CHECK (channel IS NULL OR channel IN ('email','whatsapp','voice'));
ALTER TABLE messages DROP COLUMN simulated;
UPDATE messages SET channel = 'email' WHERE channel = 'sms';
ALTER TABLE messages DROP CONSTRAINT chk_messages_channel;
ALTER TABLE messages ADD CONSTRAINT chk_messages_channel CHECK (channel IN ('email','whatsapp','voice'));
