"""One error vocabulary for HTTP and tools (LLD section 6, eng review Q2)."""

from enum import StrEnum


class ErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    STALE_DRAFT = "STALE_DRAFT"
    NOT_APPROVED = "NOT_APPROVED"
    NOT_VERIFIED = "NOT_VERIFIED"
    SENDING_DISABLED = "SENDING_DISABLED"
    FEATURE_DISABLED = "FEATURE_DISABLED"
    INVOICE_DISPUTED = "INVOICE_DISPUTED"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    INVENTED_AMOUNT = "INVENTED_AMOUNT"
    TOTAL_MISMATCH = "TOTAL_MISMATCH"
    INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND"
    INVOICE_WRONG_CUSTOMER = "INVOICE_WRONG_CUSTOMER"
    CUSTOMER_MISMATCH = "CUSTOMER_MISMATCH"
    DATE_INVALID = "DATE_INVALID"
    DATE_MISMATCH = "DATE_MISMATCH"
    TONE_UNSAFE = "TONE_UNSAFE"
    PLACEHOLDER_MISSING = "PLACEHOLDER_MISSING"
    PAYMENT_DETAILS_UNVERIFIED = "PAYMENT_DETAILS_UNVERIFIED"
    AMOUNT_UNPARSEABLE = "AMOUNT_UNPARSEABLE"
    REASON_REQUIRED = "REASON_REQUIRED"
    MESSAGE_CUSTOMER_MISMATCH = "MESSAGE_CUSTOMER_MISMATCH"
    DISPUTE_EXISTS = "DISPUTE_EXISTS"
    NO_LEDGER_EVIDENCE = "NO_LEDGER_EVIDENCE"
    CLASS_INVALID = "CLASS_INVALID"
    IDEMPOTENCY_MISMATCH = "IDEMPOTENCY_MISMATCH"
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    REPLAY_WINDOW = "REPLAY_WINDOW"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"
    LLM_UPSTREAM = "LLM_UPSTREAM"
    LLM_TIMEOUT = "LLM_TIMEOUT"
    REPLAY_MISS = "REPLAY_MISS"
    TOOL_LIMIT = "TOOL_LIMIT"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    DIRECT_DB_ATTEMPT = "DIRECT_DB_ATTEMPT"
    PROMPT_INJECTION_SUSPECTED = "PROMPT_INJECTION_SUSPECTED"
    RATE_LIMITED = "RATE_LIMITED"
    GOOGLE_NOT_CONFIGURED = "GOOGLE_NOT_CONFIGURED"
    GOOGLE_NOT_CONNECTED = "GOOGLE_NOT_CONNECTED"
    GOOGLE_UPSTREAM = "GOOGLE_UPSTREAM"
    INTERNAL = "INTERNAL"


STATUS = {
    ErrorCode.VALIDATION_ERROR: 422,
    ErrorCode.UNAUTHORIZED: 401,
    ErrorCode.FORBIDDEN: 403,
    ErrorCode.NOT_FOUND: 404,
    ErrorCode.STALE_DRAFT: 409,
    ErrorCode.NOT_APPROVED: 409,
    ErrorCode.NOT_VERIFIED: 409,
    ErrorCode.SENDING_DISABLED: 409,
    ErrorCode.FEATURE_DISABLED: 409,
    ErrorCode.INVOICE_DISPUTED: 409,
    ErrorCode.DISPUTE_EXISTS: 409,
    ErrorCode.IDEMPOTENCY_MISMATCH: 409,
    ErrorCode.SIGNATURE_INVALID: 401,
    ErrorCode.REPLAY_WINDOW: 401,
    ErrorCode.BUDGET_EXHAUSTED: 503,
    ErrorCode.LLM_UPSTREAM: 503,
    ErrorCode.LLM_TIMEOUT: 503,
    ErrorCode.REPLAY_MISS: 503,
    ErrorCode.RATE_LIMITED: 429,
    ErrorCode.GOOGLE_NOT_CONFIGURED: 409,
    ErrorCode.GOOGLE_NOT_CONNECTED: 409,
    ErrorCode.GOOGLE_UPSTREAM: 503,
    ErrorCode.INTERNAL: 500,
}


class AppError(Exception):
    """Raised by services; mapped once at the edge (HTTP) or the tool envelope."""

    def __init__(self, code: ErrorCode, message: str, details: list[dict[str, str]] | None = None) -> None:
        super().__init__(message)
        self.code, self.message, self.details = code, message, details or []

    @property
    def status(self) -> int:
        return STATUS.get(self.code, 422)  # guardrail and content errors are 422
